name: Deploy to production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: contention/rsync-deployments@v2.0.0
        with:
          EXCLUDES: --exclude .htaccess --exclude /uploads/
          USER: slyizs
          HOST: jerry.iit.uni-miskolc.hu
          LOCALPATH: /dist/
          REMOTEPATH: /home/stud2020/slyizs/public_html
          DEPLOY_KEY: ${{ secrets.ftp_password }}
